version: "3"
services:
  job-definition-api:
    build:
      context: .
    image: registry.wacodis.demo.52north.org/job-definition-api:latest
    ports:
      - 8080:8080
    environment: 
      - spring.rabbitmq.host=eum-dcsi.demo.52north.org
