version: "3"
services:
  job-definition-api:
    build:
      context: .
    image: wacodis/job-definition-api
    ports:
      - 8080:8080
    depends_on:
      - cassandra
    environment: 
      - spring.data.cassandra.contactpoints=cassandra
      - spring.data.cassandra.port=9042
    entrypoint: /bin/bash
    command: ["-c", "/wait-for-it.sh -t 30 cassandra:9042 && java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
  cassandra:
      image: cassandra:3.11
      expose:
          - "9042"
