server:
  type: simple
  applicationContextPath: /jobrepository
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
messages:
  defaultMessage: "Actually, WaCoDiS has nothing to do and that will remain!"