server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      bindings:
        jobStatus:
          destination: wacodis.jobs.status
          binder: wacodis_rabbit
          group: jobStatusConsumers
        jobCreation:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          content-type: application/json
        jobDeletion:
          destination: wacodis.jobs.deletion
          binder: wacodis_rabbit
          content-type: application/json
        jobCreationConfirm:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          group: jobCreationConsumers
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  data:
    elasticsearch:
      cluster:
        name: elasticsearch
      host: localhost
      port: 9200
      nativePort: 9300
