spring:
  cloud:
    stream:
      bindings:
        jobStatus:
          destination: wacodis.jobs.status
          binder: wacodis_rabbit
          group: jobStatusConsumers
        jobCreation:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          content-type: application/json
        jobDeletion:
          destination: wacodis.jobs.deletion
          binder: wacodis_rabbit
          content-type: application/json
        jobCreationConfirm:
          destination: wacodis.jobs.creation
          binder: wacodis_rabbit
          group: jobCreationConsumers
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: eum-dcsi.demo.52north.org
    port: 5672
    username: rabbitmq
    password: rabbitmq
  data:
    cassandra:
      port: 9042
      keyspace-name: wacodisJobDefinitions
      contactpoints: localhost
