server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    config:
      url: http://localhost:8888
    stream:
      bindings:
        job-status:
          destination: wacodis.test.jobs.status
          binder: wacodis_rabbit
          group: jobStatusConsumers
        job-creation:
          destination: wacodis.test.jobs.new
          binder: wacodis_rabbit
          content-type: application/json
        job-deletion:
          destination: wacodis.test.jobs.deleted
          binder: wacodis_rabbit
          content-type: application/json
        job-creation-confirm:
          destination: wacodis.test.jobs.new
          binder: wacodis_rabbit
          group: jobCreationConsumers
      binders:
        wacodis_rabbit:
          type: rabbit
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  data:
    elasticsearch:
      cluster:
        name: elasticsearch
      host: localhost
      port: 9200
      nativePort: 9300
